# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr:
  - master

jobs:
- job: PublishArtifacts
  pool:
     vmImage: 'ubuntu-latest'
  continueOnError: false
  steps:
  - task: PublishBuildArtifacts@1
    name: PusblishArtifact
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)'
      ArtifactName: 'networkautomation'
      publishLocation: 'Container'
